name: Delete artifact branch when pull requests are closed
on:
  pull_request:
    types: [closed]
jobs:
  hardening:
    name: Harden runner
    uses: ./.github/workflows/hardening.yaml
  delete-branch:
    name: Delete artifact branch
    needs: hardening
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Delete artifact target branch
        id: delete-artifact-target-branch
        env:
          TARGET_BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin :"tmp-$TARGET_BRANCH-artifacts" || echo "Could not delete tmp-$TARGET_BRANCH-artifacts"
